server:
  port: ${PORT:8080}
logging:
  level:
    data:
      mongodb:
        core:
          MongoTemplate: DEBUG
springdoc:
  api-docs:
    enabled: true
spring:
  main:
    banner-mode: "off"
  application:
    name: parking-control
  data:
    mongodb:
      uri: ${MONGO_URI}
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
management:
  endpoint:
    health:
      show-details: "ALWAYS"
