server:
  port: ${port:8080}

logging:
    level:
        data:
            mongodb:
                core:
                    MongoTemplate: DEBUG
springdoc:
    api-docs:
        enabled: true
spring:
    main:
        banner-mode: "off"
    application:
        name: ${name:parking-control}
    profiles:
        active: ${profiles_active:local}
    data:
        mongodb:
          uri: mongodb://localhost:27017/parking-control-ms
          field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

management:
    endpoint:
        health:
            show-details: "ALWAYS"